version: '2'
services:

  web:
    image: mario21ic/nginx-ruby23
    build:
      context: .
    volumes:
      - .:/apps/web
    command: rails server -p 3000 -b 0.0.0.0
    ports:
      - 3000:3000
