version: '2'
services:

  backend:
    image: mario21ic/nginx-php56:latest
    build:
      context: ./docker/
    volumes:
      - ./src:/app/
      - ./logs:/var/log/nginx/
    ports:
      - 80:80
