version: '2'
services:

  base:
    image: mario21ic/nginx-php56:base
    build:
      context: ./base/

  nginx:
    image: mario21ic/nginx-php56:nginx
    build:
      context: ./nginx/
    volumes:
      - ./:/app/
      - ./nginx/logs:/var/log/nginx/
    ports:
      - 80:80

  composer:
    image: mario21ic/nginx-php56:composer
    build:
      context: ./composer/
    volumes:
      - ./:/app
      - ./docker/ssh/:/app/.ssh/
    command: composer update
