version: '2'
services:

  backend:
    image: mario21ic/apache2-php53:latest
    build:
      context: ./docker/
    volumes:
      - ./src:/var/www/html/
      - ./logs/:/var/log/apache2/
    ports:
      - 80:80
